### ISSUE TITLE
copy代码后运行后出现问题，烦请解答，谢谢。

### ISSUE THREAD

**Issue by gusubuzhi** [secsilm/plotly-choropleth-mapbox-demo#1]
你好，最近我有一个小项目，需要用到地图模块。但是在copy代码本地运行后，出现一点问题。忘能解答。同事我对NLP也感兴趣，最近正在学习。以后希望能有一个领路人带着成长。谢谢。
联系方式 V信：SilenceV07

**Comment by secsilm** [comment]
你好，你可以直接把错误贴到这里。

**Comment by gusubuzhi** [comment]
--------源代码报错如下---------------
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/plotly-choropleth-mapbox-demo-master/px-choropleth-mapbox.py", line 8, in <module>
    provinces_map = json.load(f)
  File "D:\Anaconda\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 377274: illegal multibyte sequence
---------------------------------------------------------------------
以上应是编码问题，我在with open("china_province.geojson",encoding='utf-8') 加入 encoding = 'utf-8' 后，又报有如下错误：
-------------------------------- --------------------------
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/plotly-choropleth-mapbox-demo-master/px-choropleth-mapbox.py", line 10, in <module>
    df = pd.read_csv('data.csv')
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 537, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 740, in pandas._libs.parsers.TextReader._get_header
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 0: invalid continuation byte
------------------------------------------------------------------------------------------------------------------
然后，我在 df = pd.read_csv('data.csv',encoding = 'gbk')  加入 encoding = 'gbk' 后，报错如下：
--------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/plotly-choropleth-mapbox-demo-master/px-choropleth-mapbox.py", line 38, in <module>
    fig.show()
  File "D:\Anaconda\lib\site-packages\plotly\basedatatypes.py", line 3398, in show
    return pio.show(self, *args, **kwargs)
  File "D:\Anaconda\lib\site-packages\plotly\io\_renderers.py", line 404, in show
    renderers._perform_external_rendering(fig_dict, renderers_string=renderer, **kwargs)
  File "D:\Anaconda\lib\site-packages\plotly\io\_renderers.py", line 341, in _perform_external_rendering
    renderer.render(fig_dict)
  File "D:\Anaconda\lib\site-packages\plotly\io\_base_renderers.py", line 742, in render
    open_html_in_browser(html, self.using, self.new, self.autoraise)
  File "D:\Anaconda\lib\site-packages\plotly\io\_base_renderers.py", line 686, in open_html_in_browser
    server = HTTPServer(("127.0.0.1", 0), OneShotRequestHandler)
  File "D:\Anaconda\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "D:\Anaconda\lib\http\server.py", line 140, in server_bind
    self.server_name = socket.getfqdn(host)
  File "D:\Anaconda\lib\socket.py", line 756, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
--------------------------------------------------------------------------------------------------------------
最后定位问题在 fig.show() 这个函数上面。
总结:我在读取两个文件的时候，china_province.geojson 用的是UTF-8，data.csv 用的是 gbk,编码问题暂时没有问题了，但是最后在 图片显示函数的时候，显示有问题，我对其他的编码都测试过，最后对回到 fig.show()。请问这个是什么情况，谢谢。

**Comment by secsilm** [comment]
`df = pd.read_csv('data.csv',encoding = 'gbk')` 中 encoding 改为 utf8 试试，所有编码都应使用 utf8。

**Comment by gusubuzhi** [comment]
已尝试了，读取的时候，有点问题，所以我就改为 gbk。报错如下：
-----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/plotly-choropleth-mapbox-demo-master/px-choropleth-mapbox.py", line 10, in <module>
    df = pd.read_csv('data.csv',encoding = 'utf-8')
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "D:\Anaconda\lib\site-packages\pandas\io\parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 537, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 711, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 2034, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 0: invalid continuation byte

**Comment by secsilm** [comment]
我在我这里没法复现你的问题，我在 `with open("china_province.geojson") as f:` 加上 `, encoding='utf8'` 就可以了。`pd.read_csv` 这里是不需要加 `encoding` 的，`data.csv` 本身就是 utf8 编码，你在 python 解释器里，`df = pd.read_csv('data.csv')` 能运行成功吗？

**Comment by gusubuzhi** [comment]
我各种情况都尝试了，还是会报编码问题，能否加微信详细讨论一下呢？

**Comment by secsilm** [comment]
不好意思啊，比较忙不太方便加微信。

能否提供一下以下信息呢？

1. python 版本
2. 运行方式（cmd、Windows terminal、vscode、pycharm）
3. python 解释器里，`df = pd.read_csv('data.csv')` 能运行成功吗？

**Comment by gusubuzhi** [comment]
1、python版本：3.8
2、运行方式：pycharm
3、python解释器里面运行也有错误，报错为：UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

PS:因为地图这个模块对我这个项目比较重要，请问还有其他的模块可以实现在线交互么？我试过pyechart模块，但是是需要生成来连接的，我是想把地图模块放在 streamlit 模块中进行在线可视化。谢谢。

**Comment by gusubuzhi** [comment]
看报错好像是第一个位置有问题，我特意也看了第一个位置，发现也没有什么一个异常情况。

**Comment by secsilm** [comment]
1. 你有对 `data.csv` 改动过吗？
2. 你能否尝试下在 cmd 或 Windows terminal 运行试试呢？
3. 关于地图，可以尝试下 folium，其他的我也没用过

**Comment by gusubuzhi** [comment]
我刚刚读出来，但是在 fig.show() 里面报错，之前也是在这个函数里面报错，报错具体如下：
D:\Anaconda\python.exe C:/Users/admin/Desktop/plotly-choropleth-mapbox-demo-master/px-choropleth-mapbox.py
    Unnamed: 0        地区     确诊  疑似     治愈    死亡
0            0        上海    335   0    261     3
1            1   广西壮族自治区    251   0    112     2
2            2        广东   1345   0    774     6
3            3    内蒙古自治区     75   0     31     0
4            4        安徽    989   0    659     6
5            5        江苏    631   0    445     0
6            6   宁夏回族自治区     71   0     58     0
7            7        吉林     93   0     55     1
8            8        辽宁    121   0     80     1
9            9        山东    755   0    332     4
10          10        四川    527   0    265     3
11          11        湖南   1016   0    725     4
12          12        云南    174   0    124     2
13          13        湖北  64287   0  16738  2495
14          14        台湾     28   0      5     1
15          15        香港     74   0     12     2
16          16        浙江   1205   0    765     1
17          17        江西    934   0    645     1
18          18        陕西    245   0    162     1
19          19        北京    399   0    198     4
20          20        河南   1271   0    930    19
21          21        福建    293   0    174     1
22          22        河北    311   0    221     6
23          23       黑龙江    480   0    224    12
24          24        海南    168   0    106     5
25          25        重庆    575   0    335     6
26          26        山西    132   0     88     0
27          27  新疆维吾尔自治区     76   0     28     2
28          28        甘肃     91   0     78     2
29          29        天津    135   0     81     3
30          30        贵州    146   0    102     2
31          31     西藏自治区      1   0      1     0
32          32        青海     18   0     18     0
33          33        澳门     10   0      6     0

===============以上是我正确读取出来的结果=====================


Traceback (most recent call last):
  File "C:/Users/admin/Desktop/plotly-choropleth-mapbox-demo-master/px-choropleth-mapbox.py", line 39, in <module>
    fig.show()
  File "D:\Anaconda\lib\site-packages\plotly\basedatatypes.py", line 3398, in show
    return pio.show(self, *args, **kwargs)
  File "D:\Anaconda\lib\site-packages\plotly\io\_renderers.py", line 404, in show
    renderers._perform_external_rendering(fig_dict, renderers_string=renderer, **kwargs)
  File "D:\Anaconda\lib\site-packages\plotly\io\_renderers.py", line 341, in _perform_external_rendering
    renderer.render(fig_dict)
  File "D:\Anaconda\lib\site-packages\plotly\io\_base_renderers.py", line 742, in render
    open_html_in_browser(html, self.using, self.new, self.autoraise)
  File "D:\Anaconda\lib\site-packages\plotly\io\_base_renderers.py", line 686, in open_html_in_browser
    server = HTTPServer(("127.0.0.1", 0), OneShotRequestHandler)
  File "D:\Anaconda\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "D:\Anaconda\lib\http\server.py", line 140, in server_bind
    self.server_name = socket.getfqdn(host)
  File "D:\Anaconda\lib\socket.py", line 756, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
Process finished with exit code 1

**Comment by gusubuzhi** [comment]
问题解决了，多谢。

**Comment by secsilm** [comment]
方便说下是怎么回事吗😂

**Comment by gusubuzhi** [comment]
抱歉，我尝试在jupter上运行后就成功了，但是在pycharm 里面运行就报错。
因为昨天我看到好像有一个HTTP的错误，所以我就换一个地方。然后我嵌入到我的 streamlit 模块后也成功显示出来了。这几天多谢你了。

**Comment by secsilm** [comment]
好的，解决了就好，pycharm 有时就会有莫名其妙的问题。
